### ISSUE TITLE
Update instructions because RawGit is EOL

### ISSUE THREAD

**Issue by alexsavage** [wernight/powerline-web-fonts#16]
The instructions for this project need to be updated to use another CDN in front of GitHub. From the [RawGit web site](https://rawgit.com/):

>October 8, 2018
>RawGit is now in a sunset phase and will soon shut down. It's been a fun five years, but all things must end.
>
>GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served.
>
>If you're currently using RawGit, please stop using it as soon as you can.

Of the choices suggested on the RawGir page, jsDelivr seems to work for this purpose. It has a  [migration applet](https://www.jsdelivr.com/rawgit) that can help update references to use jsDelivr URLs instead of RawGit.

E.g.: https://cdn.jsdelivr.net/gh/wernight/powerline-web-fonts@ba4426cb0c0b05eb6cb342c7719776a41e1f2114/PowerlineFonts.css

**Comment by wernight** [comment]
Thanks for catching this up.

This may even require a warning in the home README that it changed.
