### ISSUE TITLE
Tmux powerline fonts still broken?

### ISSUE THREAD

**Issue by tlnagy** [wernight/powerline-web-fonts#8]
This works great with secure shell

![image](https://cloud.githubusercontent.com/assets/1661487/23829234/b0d09eea-06a1-11e7-9356-da6af1560a83.png)

but for some reason powerline fonts aren't working in tmux? any idea what might be causing this?

![image](https://cloud.githubusercontent.com/assets/1661487/23829236/cdccf066-06a1-11e7-9a1b-9b1a09e8f76a.png)

Here's my `.tmux.conf`:

```
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Fix mousing
# set -g mode-mouse on

# Vi-bindings for visual mode
setw -g mode-keys vi

# use | and - to split the windows
bind-key | split-window -h
bind-key - split-window -v

# make the first window number start at 1
set -g base-index 1

# from http://endot.org/2011/12/06/my-tmux-configuration/
# keybindings to make resizing easier
bind -r C-h resize-pane -L
bind -r C-j resize-pane -D
bind -r C-k resize-pane -U
bind -r C-l resize-pane -R

# Show pane numbers for 2s, default is too short
set -g display-panes-time 2000
set -g pane-base-index 1

# Make vim and tmux play nice together
# See README here https://github.com/christoomey/vim-tmux-navigator
is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"'
bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
bind -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
```

**Comment by wernight** [comment]
That's powerline we're talking about. I don't think tmux suports it directly. There is powerline flag to use unicode characters: https://powerline.readthedocs.io/en/master/configuration/reference.html#themes

**Comment by tlnagy** [comment]
I'm testing this out on my Mac and it works fine in iterm, it's only when I use tmux through secure shell that it breaks.

iterm local:
![image](https://cloud.githubusercontent.com/assets/1661487/23926821/b58ff3c0-08d3-11e7-92e6-08eb54a3f5d4.png)

To test I'm simply ssh-ing into `localhost` and try to see how powerline fonts work in secure shell using this repo. That's what I'm showing in the original post

**Comment by wernight** [comment]
I only use it when SSHing into remote machines and I've no issues but I'm using a Chromebook. On Mac I installed the font locally and iTerm 2 worked. If it works locally in the same terminal app, then it should be an issue with the config that is different when using SSH or such. The font used by the terminal app doesn't change and has no idea if it's local or remote.

**Comment by wernight** [comment]
The machines I SSH into also run TMux with powerline without issues with this font. You may want to upgrade or check if you change anything based on `$TERM`.

**Comment by zhigang1992** [comment]
In my case, it's because tmux wasnt using utf-8.

try 

```bash
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
```
then start tmux,

or 

```bash
tmux -u
```

**Comment by WMcKibbin** [comment]
@zhigang1992  you are my savior

**Comment by lalitmee** [comment]
@zhigang1992, Really bro it works great. I was not having any idea that `UTF-8` may be the problem. :innocent: 
Thank you so much. :smiley:

**Comment by losemyheaven** [comment]
@zhigang1992 
submarine
rocket
666

**Comment by megagon** [comment]
for anyone who can't make it work: you need to select this font in terminal's settings: 
<img width="677" alt="image" src="https://user-images.githubusercontent.com/4102581/108634038-bb332e80-7488-11eb-9cd6-ddef3c5e1346.png">
